
service: ${env:SERVICE} 

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  upladToS3:
    handler: src/handler.upload
    events:
      - http:
          method: post
          path: upload

  trggerStepFunction:
    handler: src/trigger.triggerStepFunc
    role: ${env:IAM_ROLE} 
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          existing: true


plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

resources:
  Resources:
    ImageBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${env:BUCKET_NAME}